development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tedxperth_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test: &TEST
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tedxperth_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

staging:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: localhost
  database: tedxperth_staging
  pool: 5
  username: root
  password: 

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: tedxperth_production
  pool: 5
  username: root
  password: 
  socket: /tmp/mysql.sock
