---
default:
  secret_token: ""
  rpx:
    api_key: ""
    app_id: ""
    subdomain: ""
  jsapi:
    key: ""
development:
  mailer:
    from: "mailer@tedxperth.dev"
    host: "tedxperth.dev"
    delivery_method: sendmail
test:
  mailer:
    from: "example@example.com"
    host: "example.com"
    delivery_method: test

